POST http://127.0.0.1:5000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6ImJvYiIsInR5cGUiOiJhY2Nlc3MiLCJleHAiOjE3NTE4MDM0MDEsImlhdCI6MTc1MTgwMTYwMX0.Ur-nj-2jEpEoOljxRd2uAnJ6A68gXLFGrci7QzZ9YlQ
Content-Type: application/json
{
    "title": "Some title",
    "description": "Some description"
}