GET http://127.0.0.1:5000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6ImJvYiIsInR5cGUiOiJhY2Nlc3MiLCJleHAiOjE3NTE4MDI2NDMsImlhdCI6MTc1MTgwMDg0M30.OVltWFXNgOv4jWBjqX-7PzrPtzktaLCI8TIl3kZ-QCQ
