GET http://192.168.128.61:5000/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFsaWNlIiwidHlwZSI6ImFjY2VzcyIsImV4cCI6MTc1MjUwMzI0MSwiaWF0IjoxNzUyNTAxNDQxfQ.c0B8q8hi0LLqIW6tYTelxUYECKCeuvgA6QtBd_saNfM
